name: fair-software

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .howfairis.yml
    workflow_dispatch:

  pull_request:
    paths:
      - README.md
      - .howfairis.yml

jobs:
  verify:
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - uses: fair-software/howfairis-github-action@0.2.0
        name: Measure compliance with fair-software.eu recommendations
        env:
          PYCHARM_HOSTED: "Trick colorama into displaying colored output" 
        with:
          MY_REPO_URL: "https://github.com/${{ github.repository }}"
